# Site settings
title: Fundación Ciudadano Inteligente
email: prensa@ciudadanointeligente.org
description: "Sitio web de la Fundación Ciudadano Inteligente"
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
